name: Deploy contabil-unidades

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      service-name: contabil-unidades
      deployment-name: contabil-unidades-deployment
      port: "10092"
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
